import 'style/main.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import WrapperLayiout from 'components/WrapperLayout';

const roboto = Roboto({
  weight: ['100', '400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        <WrapperLayiout>{children}</WrapperLayiout>
      </body>
    </html>
  );
}
